name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
        env:
          CI: true
      - name: Install build dependencies and build
        run: npm i && npm run build
      - name: Run tests
        run: npm run test:badges
      - name: build & publish
        run: npm run pub
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
